### ISSUE TITLE
cdk synth generates invalid YAML in Jenkins shell

### ISSUE THREAD

**Issue by bogdankatishev** [aws-solutions/distributed-load-testing-on-aws#157]
**Describe the bug**
Hello, we have encountered a weird bug within the `deployment/build-s3-dist.sh` script. When running the build scripts locally, we can generate valid templates for `distributed-load-testing-on-aws.template` and `distributed-load-testing-on-aws-regional.template`. BUT when running in a Jenkins shell environment, we receive the exact same YAML template but with **a weird INFO line** being redirected/included in the stdout. 

This is the head of our generated YAML in jenkins:
```
[Info at /RegionalInfrastructureDLTStack/Solution] Consider making this CfnMapping a lazy mapping by providing `lazy: true`: either no findInMap was called or every findInMap could be immediately resolved without using Fn::FindInMap
Description: (SO0062-regional) - Distributed Load Testing on AWS testing resources regional deployment. Version 20240122103928
Parameters:
  ExistingVPCId:
    Type: String
    AllowedPattern: (?:^$|^vpc-[a-zA-Z0-9-]+)
    Description: Existing VPC ID
...
```

We already tried redirecting output in `deployment/build-s3-dist.sh`  to a seperate stderr file with `2>`  and including arguments like `--ignore-errors true` and `--notices false` but nothing seems to work to filter out the INFO line at the beginning:
```
node_modules/aws-cdk/bin/cdk synth --ignore-errors true --notices false --asset-metadata false --path-metadata false -a "npx ts-node --prefer-ts-exts bin/${template}.ts" 2> stderr.txt 1> ${templates[$template]}/${template}.template
```

**To Reproduce**
At this moment, we can only reproduce it in Jenkins when using groovy `sh` blocks.

**Expected behavior**
When running locally, we get a valid YAML:
```
Description: (SO0062-regional) - Distributed Load Testing on AWS testing resources regional deployment. Version bogdantest
Parameters:
  ExistingVPCId:
    Type: String
    AllowedPattern: (?:^$|^vpc-[a-zA-Z0-9-]+)
    Description: Existing VPC ID
...
```

**Please complete the following information about the solution:**
- [ ] Version: [3.2.4]
- [ ] Region: [e.g. eu-west-1]
- [ ] Was the solution modified from the version published on this repository? Only the `deployment/build-s3-dist.sh` with the additional cdk args ` --ignore-errors true --notices false`
- [ ] Were there any errors in the CloudWatch Logs? Yes, invalid yaml error:
```
com.amazonaws.services.cloudformation.model.AmazonCloudFormationException: Template format error: YAML not well-formed
```
