### ISSUE TITLE
The importance of DLT custom resources

### ISSUE THREAD

**Issue by khiliel** [aws-solutions/distributed-load-testing-on-aws#183]
Hello!

I was wondering if any of you could explain the custom resources used in DLT as I do not understand how they work completely and the importance of them in this use case. I ask because for my enterprise, I am removing certain things that may be un-needed for our use case. For example, in the "DLTCustomResourcesTestingResourcesConfig0BCA657F" resource, could you explain whats happening here and the importance? I removed the pieces in the template that allows it to create vpc and its resources upon request to make sure teams use our vpc process instead. This includes the fargate condition, the fargate vpc creation, the subnets... etc. Below is how the custom resource looks after I made my changes, I am getting an error now due to the fn::if not having a third parameter. Any guidance?

```
DLTCustomResourcesTestingResourcesConfig0BCA657F:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - DLTCustomResourceInfraCustomResourceLambdaA4053269
          - Arn
      TestingResourcesConfig:
        region:
          Ref: AWS::Region
        subnetA:
          Fn::If:
            - CreateFargateVPCResources
            - Ref: ExistingSubnetA
        subnetB:
          Fn::If:
            - CreateFargateVPCResources
            - Ref: ExistingSubnetB
        ecsCloudWatchLogGroup:
          Ref: DLTEcsDLTCloudWatchLogsGroupFE9EC144
        taskSecurityGroup:
          Ref: DLTEcsDLTEcsSecurityGroup69E6743C
        taskDefinition:
          Ref: DLTEcsDLTTaskDefinition6BFC2400
        taskImage:
          Fn::Join:
            - ""
            - - Ref: AWS::StackName
              - -load-tester
        taskCluster:
          Ref: DLTEcsDLTEcsClusterBC5CE23B
      Resource: TestingResourcesConfigFile
      Uuid:
        Fn::GetAtt:
          - DLTCustomResourcesCustomResourceUuidD1C03F15
          - UUID
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
   ```
