### ISSUE TITLE
Is it still possible to use load test scenario yaml file?

### ISSUE THREAD

**Issue by tanvp112** [aws-solutions/distributed-load-testing-on-aws#60]
In previous version it is possible to create a load test yaml file and run thru CodePipeline. Is it still possible to do that in this version? If there is can you please point me to the documentation as I can't find it in the official implementation guide.

It will be even better if there a place on the UI where we can upload a **list of scenarios** (not JMX thread groups).

Thanks!

**Comment by emcfins** [comment]
Apologies for the delay in response.
Can you go through the process you used to use to use a load test yaml file for your tests in previous versions? 
And can yo provide a sample yaml file that you're looking to use?

**Comment by tanvp112** [comment]
Take a look here https://github.com/aws-samples/distributed-load-testing-using-aws-fargate

**Comment by emcfins** [comment]
That is a different version of the solution and do not create tests in the same fashion so it does not support bringing you own test scenario.

What is the limitation you're running into that you are unable to use the new solution? I'd like to add this item to the backlog and having details around your use case would be helpful.

**Comment by G-Lenz** [comment]
Closing this issue due to inactivity, feel free to re-open if this is still an issue.

**Comment by minotier89** [comment]
We have the same problem.
We have multiple JMeter scenarios as shown below (there are 6 scenarios) and we want to specify parameters, select Yaml for Taurus, but there did not seem to be a section to set these.

Please let me know if there is a way to specify the Yaml or these parameters.
```
modules:
  jmeter:
    properties:
      num_threads1: 1
      num_threads2: 2
      num_threads3: 3
      num_threads4: 4
      num_threads5: 5
      num_threads6: 6
      sec_rumpup1: 60
      sec_rumpup2: 60
      sec_rumpup3: 60
      sec_rumpup4: 60
      sec_rumpup5: 60
      sec_rumpup6: 60
      sec_duration: 180
execution:
  - scenario:
      script: ./scenarios/All.jmx
      throughput: 10
```
